#! /bin/bash

#(C) 2009 C. Junghans
# junghans@mpip-mainz.mpg.de

#version 0.1  04.08.10 -- initial version

BLUE="[34;01m"
CYAN="[36;01m"
CYANN="[36m"
GREEN="[32;01m"
RED="[31;01m"
PURP="[35;01m"
OFF="[0m"

usage="Usage: ${0##*/} [OPTIONS] -- [ARGS]"
quiet="no"
diff="no"
filter="no"
diff_opts='--new-file --unified --show-c-function --recursive'
wdiff_opts="--start-delete=$RED --end-delete=$OFF --start-insert=$GREEN --end-insert=$OFF"

die() {
  echo -e "$*"
  exit 1
}

qecho() {
  [ "$quiet" = "yes" ] || echo -e "$*"
}

show_help () {
  cat << eof
This colorized the output of wdiff
$usage
ARGS will be given to wdiff (no ARGS = read from stdin)
OPTIONS:
-f, --filter        Just act as a filter (don't run wdiff internally)
                    ARGS will be given to sed (no ARGS = read from stdin)
-d, --diff          Preprocess input with diff (useful for dirs)
                    ARGS will be given to diff (no ARGS = read from stdin)
    --diffopts XXX  Change opts of diff
                    Default: '$diff_opts'
    --no-color      Disable-color
-h, --help          Show this help
-v, --version       Show version
    --hg            Show last log message for hg (or cvs)

Examples:  ${0##*/} -q
           ${0##*/}

Send bugs and comment to junghans@mpip-mainz.mpg.de
eof
}

while [ "${1#-}" != "$1" ]; do
 if [ "${1#--}" = "$1" ] && [ -n "${1:2}" ]; then
    #short opt with arguments here: fc
    if [ "${1#-[fc]}" != "${1}" ]; then
       set -- "${1:0:2}" "${1:2}" "${@:2}"
    else
       set -- "${1:0:2}" "-${1:2}" "${@:2}"
    fi
 fi
 case $1 in 
   --no-color)
    unset BLUE CYAN CYANN GREEN RED PURP OFF
    wdiff_opts=""
    shift;;
   -f | --filter)
    filter="yes"
    shift ;;
   -d | --diff)
    diff="yes"
    shift ;;
   --diffopts)
    diff_opts="$1"
    shift ;;
   -q | --quiet)
    quiet="yes"
    shift ;;
   -h | --help)
    show_help
    exit 0;;
   --hg)
    echo "${0##*/}: $(sed -ne 's/^#version.* -- \(.*$\)/\1/p' $0 | sed -n '$p')"
    exit 0;;
   -v | --version)
    echo "${0##*/}, $(sed -ne 's/^#\(version.*\) -- .*$/\1/p' $0 | sed -n '$p') by C. Junghans"
    exit 0;;
   --)
    shift
    break;;
  *)
   die "Unknown option '$1'";;
 esac
done

if [ "$filter" = "yes" ]; then
  sed -e "s/\[-/$RED/g" \
      -e "s/-\]/$OFF/g" \
      -e "s/{+/$GREEN/g" \
      -e "s/+}/$OFF/g" "$@"
  exit $?
fi

if [ "$diff" = "yes" ]; then
  diff $diff_opts $@ | wdiff $wdiff_opts --diff-input
  exit $?
else
  [ -z "$1" ] && wdiff_opts="$wdiff_opts --diff-input"
  wdiff $wdiff_opts $@
  exit $?
fi
